apiVersion: v2
name: promyze
type: application
version: 0.5.0
appVersion: 4.14.0
description: Raise your own best coding practices with Promyze
home: https://github.com/promyze/helm-charts
maintainers:
  - name: cteyton
    email: cedric.teyton@promyze.com
icon: https://promyze.com/wp-content/uploads/promyze-rocket.png
