apiVersion: v2
name: promyze
description: A Promyze Helm chart for Kubernetes
type: application
version: 0.2.0
appVersion: 4.11.1
description: Raise your own best coding practices with Promyze
home: https://github.com/promyze/helm-charts
maintainers:
  - name: cteyton
    email: cedric.teyton@promyze.com
icon: https://promyze.com/wp-content/uploads/promyze-rocket.png