apiVersion: v2
name: promyze
description: A Promyze Helm chart for Kubernetes
type: application
version: 0.2.0
appVersion: 4.11.1
#dependencies:
#  - name: mongodb
#    version: 12.1.16 # MongoDB 5.0.9
#    repository: https://charts.bitnami.com/bitnami
#    alias: mongodb
#    condition: mongodb.enabled
maintainers:
  - name: cteyton
    email: cedric.teyton@promyze.com
